/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

/**
 *
 * @author kenda
 */
public class jmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jmPrincipal
     */
    public jmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btIngresar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btIngresarMate = new javax.swing.JButton();
        btEliminarMate = new javax.swing.JButton();
        btnee = new javax.swing.JButton();
        btnModMat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btIngresar.setBackground(new java.awt.Color(204, 204, 204));
        btIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btIngresar.setForeground(new java.awt.Color(0, 102, 102));
        btIngresar.setText("Insertar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });

        btModificar.setBackground(new java.awt.Color(204, 204, 204));
        btModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btModificar.setForeground(new java.awt.Color(0, 102, 102));
        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Estudiantes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Materias");

        btIngresarMate.setBackground(new java.awt.Color(204, 204, 204));
        btIngresarMate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btIngresarMate.setForeground(new java.awt.Color(0, 102, 102));
        btIngresarMate.setText("Insertar");
        btIngresarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarMateActionPerformed(evt);
            }
        });

        btEliminarMate.setBackground(new java.awt.Color(204, 204, 204));
        btEliminarMate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEliminarMate.setForeground(new java.awt.Color(0, 102, 102));
        btEliminarMate.setText("Eliminar");
        btEliminarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarMateActionPerformed(evt);
            }
        });

        btnee.setBackground(new java.awt.Color(204, 204, 204));
        btnee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnee.setForeground(new java.awt.Color(0, 102, 102));
        btnee.setText("Eliminar");
        btnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneeActionPerformed(evt);
            }
        });

        btnModMat.setBackground(new java.awt.Color(204, 204, 204));
        btnModMat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModMat.setForeground(new java.awt.Color(0, 102, 102));
        btnModMat.setText("Modificar");
        btnModMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btIngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIngresarMate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminarMate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIngresarMate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btIngresar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModificar)
                    .addComponent(btnModMat))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnee)
                    .addComponent(btEliminarMate))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:
        
        jmIngresar ing = new jmIngresar();
        ing.show();
        dispose();
    }//GEN-LAST:event_btIngresarActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        jfModificar mod = new jfModificar();
        mod.show();
        dispose();
    }//GEN-LAST:event_btModificarActionPerformed

    private void btIngresarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarMateActionPerformed
        // TODO add your handling code here:
        jfIngresarMateria ingMa = new jfIngresarMateria();
        ingMa.show();
        dispose();
    }//GEN-LAST:event_btIngresarMateActionPerformed

    private void btneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneeActionPerformed
         jEliminaEst es  = new jEliminaEst();
         es.show();
         dispose();
    }//GEN-LAST:event_btneeActionPerformed

    private void btnModMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModMatActionPerformed
        jModificarMat mod = new jModificarMat();
        mod.show();
        dispose();
    }//GEN-LAST:event_btnModMatActionPerformed

    private void btEliminarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarMateActionPerformed
        jEliminaMat elmat = new jEliminaMat();
        elmat.show();
        dispose();
    }//GEN-LAST:event_btEliminarMateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminarMate;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btIngresarMate;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btnModMat;
    private javax.swing.JButton btnee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
